---
# vars for datadisk-n01017431 role

disk_device: /dev/sdc

part1:
  number: 1
  start: 1MiB
  end: 4097MiB
  fstype: xfs
  mount: /part1

part2:
  number: 2
  start: 4097MiB
  end: 9217MiB
  fstype: ext4
  mount: /part2
